# Generated by Django 6.0 on 2025-12-28 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='bugs_fixed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devuser',
            name='focus_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='devuser',
            name='prs_merged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devuser',
            name='streak_days',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
