# Generated by Django 6.0 on 2026-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devuser_bugs_fixed_devuser_focus_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
